version: '3'
services: 
  heron-redux:
    build: 
      context: . 
    ports:
     - "3000:80"
    volumes:
     - /home/node/app/node_modules
     - .:/home/node/app
    command: ["npm", "run", "test"] #alternative do docker exec -it contID npm run test on running container
                                    # docker exec allows entering specific cmds for file names but not in compose