version: '3'
services: 
  heron-redux:
    build: 
      context: .
      dockerfile: Dockerfile.dev 
    ports:
     - "3000:3000"
    volumes:
     - /home/node/app/node_modules
     - .:/home/node/app
  tests: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"] #alternative do docker exec -it contID npm run test on running container
                                    # docker exec allows entering specific cmds for file names but not in compose