apiVersion: v1
kind: Service
metadata:
  name: heron-service
  labels:
    app: heron-redux
spec:
  type: NodePort
  selector:
    app: heron-redux
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
      name: http
